---
- name: update APP_URL in .env file
  lineinfile:
    path: "{{ workspace }}/.env"
    regexp: '^APP_URL='
    line: APP_URL={{ protocol }}://{{ domain }}

- name: render xdebug config from template
  template:
    src: xdebug.ini.j2
    dest: /vagrant/bin/20-xdebug.ini
    owner: www-data
    group: www-data
    mode: '0777'
  vars:
    host: "{{ domain }}"

- name: render setup script from template
  template:
    src: setup.sh.j2
    dest: /vagrant/bin/setup.sh
    owner: www-data
    group: www-data
    mode: '0755'
  vars:
    host: "{{ domain }}"

- name: setup port forwarding for xdebug
  become: yes
  command: sysctl net.ipv4.ip_forward=1 && iptables -t nat -A PREROUTING -p tcp --dport 9000 -j DNAT --to-destination 10.0.2.2:9000 && iptables -t nat -A POSTROUTING -j MASQUERADE

- name: copy setup files into shopware container
  command: docker cp /vagrant/bin/. shopware:/var/www/
