---
- name: Copy docker-compose.yml from template
  template:
    src: "docker-compose.yml.j2"
    dest: "/vagrant/docker-compose.yml"
  vars:
    version: "{{ shopware_version }}"

- name: Tear down existing services
  become: yes
  docker_compose:
    project_src: /vagrant
    state: absent

- name: Remove workspace directory
  become: yes
  file:
    path: "{{ workspace }}"
    state: absent

- name: Start docker services
  become: yes
  docker_compose:
    project_src: /vagrant

- name: Create workspace directory
  file:
    path: "{{ workspace }}"
    state: directory
    mode: '0775'
    owner: vagrant

- name: Copy document root to workspace
  become: yes
  command: docker cp shopware:/var/www/html/. "{{ workspace }}"

- name: Change ownership of workspace
  become: yes
  file:
    path: "{{ workspace }}"
    state: directory
    recurse: yes
    owner: vagrant
    group: www-data

- name: Install adyen-shopware6 plugin
  command: composer require adyen/adyen-shopware6
  args:
    chdir: "{{ workspace }}"
  register: plugin_installed
  when: plugin_installed is not defined

- name: Change ownership of plugin directories
  become: yes
  file:
    path: "{{ workspace }}/vendor/adyen"
    state: directory
    recurse: yes
    owner: vagrant
    group: www-data

- name: Expand write access for var directory
  become: yes
  file:
    path: "{{ workspace }}/var"
    recurse: yes
    mode: a+w

- name: Replace docker-compose.yml with workspace mount template
  template:
    src: "docker-compose.yml.mount.j2"
    dest: "/vagrant/docker-compose.yml"
  vars:
    version: "{{ shopware_version }}"
    directory: "{{ workspace }}"

- name: Restart docker services
  become: yes
  docker_compose:
    project_src: /vagrant
    build: yes
    restarted: yes
