---
- name: Copy docker-compose.yml from template
  template:
    src: "docker-compose.yml.j2"
    dest: "/vagrant/docker-compose.yml"
  vars:
    version: "{{ shopware_version }}"

- name: Tear down existing services
  docker_compose:
    project_src: /vagrant
    state: absent

- name: Start docker services
  docker_compose:
    project_src: /vagrant
  register: output

- name: Create workspace directory
  file:
    path: "{{ workspace }}"
    state: directory
    mode: '0775'
    owner: vagrant

- name: Copy document root to workspace
  command: docker cp shopware:/var/www/html/. "{{ workspace }}"

- name: Change ownership of workspace
  file:
    path: "{{ workspace }}"
    state: directory
    recurse: yes
    owner: vagrant
    group: www-data

- name: Expand write access for var directory
  file:
    path: "{{ workspace }}/var"
    recurse: yes
    mode: a+w

- name: Replace docker-compose.yml with workspace mount template
  template:
    src: "docker-compose.yml.mount.j2"
    dest: "/vagrant/docker-compose.yml"
  vars:
    version: "{{ shopware_version }}"
    directory: "{{ workspace }}"

- name: Restart docker services
  docker_compose:
    project_src: /vagrant
    build: yes
    restarted: yes
  register: output