---
- name: copy docker-compose.yml from template
  template:
    src: "docker-compose.yml.j2"
    dest: "/vagrant/docker-compose.yml"
  vars:
    version: "{{ shopware_version }}"

- name: start docker services
  docker_compose:
    project_src: /vagrant
    remove_orphans: yes
  register: output

- name: Create source code directory on host vm
  file:
    path: "{{ workspace }}"
    state: directory
    mode: '0775'
    owner: vagrant
    group: www-data

- name: copy document root to host
  command: docker cp shopware:/var/www/html/. "{{ workspace }}"

- name: Recursively change ownership of a directory
  file:
    path: "{{ workspace }}"
    state: directory
    recurse: yes
    owner: vagrant
    group: www-data

- name: Expand write access for var directory
  file:
    path: "{{ workspace }}/var"
    recurse: yes
    mode: a+w

- name: replace docker-compose.yml with workspace mount template
  template:
    src: "docker-compose.yml.mount.j2"
    dest: "/vagrant/docker-compose.yml"
  vars:
    version: "{{ shopware_version }}"
    directory: "{{ workspace }}"

- name: restart docker services
  docker_compose:
    project_src: /vagrant
    build: yes
    restarted: yes
  register: output