---
- name: comment out document root volume mount
  command: chdir=/vagrant sed -i 's+- "/vagrant/shopware:/var/www/html"+#- "/vagrant/shopware:/var/www/html"+g' docker-compose.yml

- name: start docker services
  become: yes
  docker_compose:
    project_src: /vagrant
    remove_orphans: yes
  register: output

- name: Create source code directory on host vm
  file:
    path: /vagrant/shopware
    state: directory
    mode: '0755'
    owner: vagrant
    group: www-data

- name: copy document root to host
  command: docker cp shopware:/var/www/html/. /vagrant/shopware

- name: Change access to var directory
  command: chdir=/vagrant sudo chmod -R a+w shopware/var/*

- name: restore document root volume mount
  command: chdir=/vagrant sed -i 's+#- "/vagrant/shopware:/var/www/html"+- "/vagrant/shopware:/var/www/html"+g' docker-compose.yml

- name: restart docker services
  docker_compose:
    project_src: /vagrant
    build: yes
    restarted: yes
  register: output